development:
  adapter: mysql
  database: online_screening_dev
  username: infibeam
  password: infibeam
  host: localhost
test:
  adapter: mysql
  database: online_screening_dev
  username: infibeam
  password: infibeam
  host: localhost
production:
  adapter: mysql
  database: online_screening_dev
  username: infibeam
  password: infibeam
  host: localhost
