# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f9dfda4499d7ef87457c01617c269c91d69484a9199356d971b7f56266fa825f0ce843ee2a0ad4377cac6f71e9e5e362659b8fc06e7df526a0fa1164ce1bbe2

test:
  secret_key_base: d37cde919a62c1af7fd77896684497774fbee344d9c7138584190c5e9f51c8b5d4c5bf4c6b4c402262ffd5450a8c5dce434201a78b62d9c77797b0475c5d7f40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
